### ISSUE TITLE
Missing space between sections

### ISSUE THREAD

**Issue by c-x** [bashtage/sphinx-material#105]
I am using this wonderful theme with Sphinx 4.0.2 but I have difficulties to reproduce the menu as showcased on https://bashtage.github.io/sphinx-material/index.html

I don't have any space between sections, which makes the menu hardly readable.

Expected results:
![Expected Results](https://user-images.githubusercontent.com/1864136/120096596-a96ac280-c12c-11eb-8aad-6b3fa7e8ae23.png)

Actual restults:
![No space sections](https://user-images.githubusercontent.com/1864136/120096604-ae2f7680-c12c-11eb-855e-e40abfe8e382.png)

So, what's the right `toctree:` to produce this menu ? Or is this a bug ?

Thanks!

**Comment by c-x** [comment]
Unfortunately this is what I did, and it doesn't work :)

**Comment by bashtage** [comment]
Build the docs that come with the project -- you should get exactly what is on the docs site.  Where is your code?
