### ISSUE TITLE
Documentation for "logo_icon"

### ISSUE THREAD

**Issue by kebekus** [bashtage/sphinx-material#112]
Dear Bashtage,

I am struggling a bit with the customization option "logo_icon". At present, the documentation says only this:

>  Set the logo icon. Should be a pre-escaped html string that indicates a unicode point, e.g., '&#xe869' which is used on this site.

I guess that "unicode point" refers to a certain font, but I do not know which font. May I ask you to update the documentation to explain this? That would be extremely helpful. Also, it is not clear to me if it is possible to use my own icon here. Again, any help would be greatly appreciated.

Best,

Stefan

**Comment by bashtage** [comment]
When using a code point, it defaults to the Material Icons font.  You can use an SVG file instead, which is what is done on most sites I am involved with. See #113

**Comment by bashtage** [comment]
I added some text here:

https://bashtage.github.io/sphinx-material/devel/customization.html

I'm going to close, but please let me know if this isn't enough.

**Comment by kebekus** [comment]
Perfect! Thank you so much for this helpful explanation.

Stefan.
