### ISSUE TITLE
ENH: allow for image file as `logo_icon`?

### ISSUE THREAD

**Issue by nickeubank** [bashtage/sphinx-material#113]
Any chance of allowing for arbitrary images as logos?

**Comment by bashtage** [comment]
You can use an SVG.

Here is an example from a project of mine:

https://github.com/bashtage/arch/blob/71c7bef92b0ddf36f627344a26f24abf7b1e5346/doc/source/conf.py#L167

**Comment by nickeubank** [comment]
WOOHOO! Thanks.
