### ISSUE TITLE
Bold code font is wider than non-bold (on Firefox)

### ISSUE THREAD

**Issue by mgeier** [bashtage/sphinx-material#15]
Same issue as https://github.com/typlog/sphinx-typlog-theme/issues/17

See for example https://nbsphinx.readthedocs.io/en/material-theme/code-cells.html#ANSI-Colors

**Comment by bashtage** [comment]
Firefox specific? Could it be a layout bug in firefox?

Chrome looks fine:

![image](https://user-images.githubusercontent.com/5585221/70263479-5bbb0700-178e-11ea-9078-c58bdcaa2e01.png)

But (non-chromium) Edge

![image](https://user-images.githubusercontent.com/5585221/70263541-860cc480-178e-11ea-8ab3-5ca18c2c562e.png)

**Comment by mgeier** [comment]
> Firefox specific?

Yes.

> Could it be a layout bug in firefox?

IDK, other themes work fine.

**Comment by bashtage** [comment]
It is driven by Roboto Mono.  If you take this fond out of the list of fonts then the issue goes away.  Workaround is to define your own fonts I suppose.  Long-term might be possible to increase the number of font-weights downloaded form google fonts.

**Comment by bashtage** [comment]
Just pushed 0.0.17 with additional font-weight support.  Could you let me know if this fixes it?

**Comment by bashtage** [comment]
Seems to fix it. Your page rendered on FF with the additional font weights

![image](https://user-images.githubusercontent.com/5585221/70286209-3a740e00-17c2-11ea-9e59-82b6864b4e68.png)

**Comment by mgeier** [comment]
Cool, thanks!

I've re-built the docs on RTD and now it works as expected in Firefox: https://nbsphinx.readthedocs.io/en/material-theme/code-cells.html#ANSI-Colors

**Comment by bashtage** [comment]
Great.  Thanks for the report.
