### ISSUE TITLE
State of GitLab integration

### ISSUE THREAD

**Issue by carrascomj** [bashtage/sphinx-material#19]
Hi! I am using this sphinx theme for a project documentation in GitLab. 

I have noticed that in the documentation there is an option in `html_theme_options` to change the repository type (`repo_type`) to one of "github"; "gitlab" or "bitbucket". However, when I set it to "gitlab" (having specified the `repo_url`, of course), I don't get an icon nor the starts/forks of the project (just the title of the project), as I would in the GitHub counterpart.

Is that the expected behavior for now or am I doing something wrong?

This is the schema of my current HTML options in _conf.py_:

```python
html_theme_options = {
    # Set the name of the project to appear in the navigation.
    "nav_title": "repo",
    "repo_url": "url to gitlab package",
    "repo_name": "repo_name",
    "repo_type": "gitlab",
    "html_minify": False,
    "html_prettify": True,
    "css_minify": True,
    "globaltoc_depth": 2,
    "color_primary": "green",
    "color_accent": "light-green",
    "theme_color": "#2196f3",
    "master_doc": False,
    "heroes": {
          ...
    },
}
```

Thank you!

**Comment by bashtage** [comment]
TBH I haven't tried anythign other than github.  A bug no doubt.

**Comment by bashtage** [comment]
Initial.  Fix is pending. It is a bit heavy-handed, and can be improved no doubt.

**Comment by carrascomj** [comment]
Nice, now it displays GitLab's icon. Thank you so much for the quick fix!
