### ISSUE TITLE
Improve version dropdown

### ISSUE THREAD

**Issue by bashtage** [bashtage/sphinx-material#22]
- [ ] Minimize javascript 
 - [ ] Reconsider location and spacing
 - [ ] Reduce to side bar for responsive

**Comment by snim2** [comment]
This feature is extremely cool, and it's something that doesn't exist in `mkdocs-material`. It would be great to have some more detailed documentation to go with it, especially documentation that does not rely on `gh-pages`.

**Comment by bashtage** [comment]
Right not it is pretty specific to statsmodels. I would like to make it more generic and allow the metadata to be set in conf.py, rather than reading a special json file like this one:

https://github.com/statsmodels/statsmodels.github.io

Ideally, the dropdown would be something like a dict where the keys were what is displayed and the values are the location of the page to redirect to.  For statsmodels, it would look like

```
other_versions = {
"stable":"/stable/",
"development":"/devel/"
"v0.6.1":"/0.6.1/",
}
```

This would allow external links as well.
