### ISSUE TITLE
Image file for logo_icon

### ISSUE THREAD

**Issue by MaxHalford** [bashtage/sphinx-material#29]
Hey, just wondering if `logo_icon` is intended to work with image files (e.g., an SVG file)? I've tried passing a path but it didn't work. I'm aware that I can override the HTML template but I thought it might be nice to support this out of the box.

**Comment by bashtage** [comment]
It works:

https://www.statsmodels.org/

See

https://github.com/statsmodels/statsmodels/blob/2036060689acb0154fe3a62067adaebf348706c7/docs/source/conf.py#L213

**Comment by bashtage** [comment]
https://github.com/statsmodels/statsmodels/blob/2036060689acb0154fe3a62067adaebf348706c7/docs/source/images/statsmodels-logo-v2-bw.svg

**Comment by MaxHalford** [comment]
Cheers @bashtage, I missed that.
