### ISSUE TITLE
Wrong "title" for "previous" and "next" buttons

### ISSUE THREAD

**Issue by mgeier** [bashtage/sphinx-material#31]
Unless the title of the previous/next page happens to be "Material"/"Admonition", respectively.

https://github.com/bashtage/sphinx-material/blob/3b65e7411ab8265d31bab13fc7adafaa5ff8d494/sphinx_material/sphinx_material/layout.html#L130

https://github.com/bashtage/sphinx-material/blob/3b65e7411ab8265d31bab13fc7adafaa5ff8d494/sphinx_material/sphinx_material/layout.html#L144

Those titles appear when hovering over the buttons/links.

**Comment by bashtage** [comment]
Thanks.
