### ISSUE TITLE
"productionlist" is messed up

### ISSUE THREAD

**Issue by mgeier** [bashtage/sphinx-material#32]
Example code: https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#grammar-production-displays

**Comment by bashtage** [comment]
Pretty bad:

![image](https://user-images.githubusercontent.com/5585221/78642804-30b30200-78ab-11ea-8309-567aeb4f740b.png)

**Comment by bashtage** [comment]
Closed by #39
