### ISSUE TITLE
Captions Not Rendering as Expected in globaltoc

### ISSUE THREAD

**Issue by ScriptAutomate** [bashtage/sphinx-material#48]
### Issue

When the index has multiple tocs, with their own captions, the **globaltoc** only shows the last caption.

### Expected Behavior

That the captions will be rendered as expected.

### Example

```rst
.. include:: ../README.rst

.. toctree::
   :caption: Theme Documentation
   :maxdepth: 2

   installing
   configuring
   contributing

.. toctree::
   :maxdepth: 1
   :hidden:

   changelog

.. toctree::
    :maxdepth: 2
    :numbered:
    :caption: Demo Documentation

    demo/structure
    demo/demo
    demo/lists_tables
    demo/api

.. toctree::
    :maxdepth: 3
    :numbered:
    :caption: This is an incredibly long caption for a long menu

    demo/long
```

This will not render properly. It will go through each `toctree` and grab the listed documents, but not include the captions. Instead, only the _last_ caption is rendered. Looking at the [Ansible documentation that is using Read The Docs theme](https://docs.ansible.com/ansible/latest/index.html), the captions render properly when using that theme but not when using Material.

Is this something that can be fixed, or added as a supported feature? It looks like the [globaltoc file](https://github.com/bashtage/sphinx-material/blob/290215c57cb6684ae92a61685fb9619942ca92fa/sphinx_material/sphinx_material/globaltoc.html) would need to be edited.

**Comment by bashtage** [comment]
There is a fix in #49.  It creates a different set of issues, but these are cosmetic rather than content, and content is more important than cosmetic I think.
