### ISSUE TITLE
ENH: Improve slide out menu on mobile with multiple TOC trees

### ISSUE THREAD

**Issue by bashtage** [bashtage/sphinx-material#50]
The global toctree does not always render very well on mobile after #49 . This should be improved.

**Comment by ScriptAutomate** [comment]
Just noticed this, too. The more captions/tocs, the more embedded scroll bars will populate the mobile / smaller-window user experience. This makes it difficult when certain tocs have many topics, as the scroll bar for that particular toc will be small, and difficult to view particular sections.

Would the goal be to have a single scroll bar, as opposed to one per toc in the global toctree in mobile view?

**Comment by bashtage** [comment]
The single list worked well; the only loss was the title of each section. I think the best approach would be to a single list with section titles as part of the list.
