### ISSUE TITLE
Custom theme color

### ISSUE THREAD

**Issue by RomeoDespres** [bashtage/sphinx-material#53]
Hi, first off, thanks for this amazing project!
Is there a way to set `primary_color` to a custom hex value? Material-UI implementations usually allow it but it doesn't seem to work to simply write `primary_color = '#0062ab'` in `conf.py`.

**Comment by bashtage** [comment]
This is derived from material for mkdocs, which supports a limited pallatte.

https://squidfunk.github.io/mkdocs-material/getting-started/#primary-color

I don't think it is possible to enable this since a lot of the CSS is precomputed for the named colors.

**Comment by RomeoDespres** [comment]
I see, thanks for the quick answer :)

**Comment by Yura52** [comment]
Hi!

> https://squidfunk.github.io/mkdocs-material/getting-started/#primary-color

I see that "black" is supported in mkdocs, but is not mentioned in color settings (and it doesn't work, I tried):
https://bashtage.github.io/sphinx-material/customization.html Is it "bug"?

**Comment by bashtage** [comment]
This color wasn't available the last time css was synced. PRs are welcome.

**Comment by Yura52** [comment]
If I understand correctly, this is the source: https://github.com/squidfunk/mkdocs-material/blob/d1147786369ccae17d915e6301be5e03e7011c6f/src/assets/stylesheets/palette/_primary.scss

And these files need to be synced:
- https://github.com/bashtage/sphinx-material/blob/master/sphinx_material/sphinx_material/static/stylesheets/application-palette.css
- https://github.com/bashtage/sphinx-material/blob/master/sphinx_material/sphinx_material/static/stylesheets/application-fixes.css

Is it correct? If so, then the "source" and the "target" look quite different in terms of structure (and the "black" color is even processed separately in the mkdocs-theme), how did you sync them before?
