### ISSUE TITLE
Unrecognised nav_name parameter

### ISSUE THREAD

**Issue by MaxHalford** [bashtage/sphinx-material#6]
Hey, great work on this.

I just tried it out and got the following error when running `make html`: `WARNING: unsupported theme option 'nav_name' given`

**Comment by bashtage** [comment]
I think it is `nav_title`.  The "real" (authoritative) list of options is here:

https://github.com/bashtage/sphinx-material/blob/master/sphinx_material/sphinx_material/theme.conf

**Comment by bashtage** [comment]
Thanks for letting me know.

**Comment by MaxHalford** [comment]
Right, nice to know! I'm currently updating the documentation of [creme](https://github.com/creme-ml/creme) to use your theme :)
