### ISSUE TITLE
Encrypted GitHub deploy key in repo?

### ISSUE THREAD

**Issue by ScriptAutomate** [bashtage/sphinx-material#62]
It's bad security practice to save any secrets, encrypted or otherwise, within a code repository:
- https://github.com/bashtage/sphinx-material/blob/master/github_deploy_key_bashtage_sphinx_material.enc

I'm not sure what you are using it for, but it may be a good idea to look into alternative means of whatever it is used for (and potentially recreate whatever the key is meant for). GitHub Actions may have what you are looking for, if it is meant to work with the GitHub API. You can use secrets in CI tooling without needing to save them to a code repository.

**Comment by bashtage** [comment]
This is standard for doctr. It pushes to gh-pages from Travis.

**Comment by bashtage** [comment]
xref drdoctr/doctr/351

**Comment by bashtage** [comment]
Going to close since this isn't easy to fix. I am assuming that the deployment key is safe for now.
