### ISSUE TITLE
Documentation on How Versions Display Works

### ISSUE THREAD

**Issue by ScriptAutomate** [bashtage/sphinx-material#63]
I'd like to know if there is some documentation I can follow to properly make use of `versioneer.py` and `_version.py` when it comes to properly versioning my repo/docs.

Since it looks like an understanding of that implementation is a prerequisite in understanding how to make use of `docs/_static/versions.json` and the version settings in the `html_theme_options`.

It looks like the tooling helps tag a point in the repo tied to that version, and that the `versions.json` helps dictate which versions ultimately become available as documentation to generate and view on the generated website. Though, I don't know how to make use of this in the best way that ensures a working site with versions.

If there is a how-to or tutorial somewhere on how this is managed by this repo and by sites making use of the version management (like https://www.statsmodels.org/stable/index.html), I'd love to test it out and implement it in my own deployments.

**Comment by bashtage** [comment]
`versioneer.py` is a package versioning system that uses git tags and commits to automatically compute version strings. These are invariant to what you sound like you are trying to do.

What matters is that you have multiple versions of your documents.  Suppose you have 1.0, 1.1 and 2.0, then you would organize your webserver like

index.html->stable/index.html
1.0/
1.1/
2.0/
stable/->symlink to latest version directory
devel/ -> optional development docs (or dev, development, or similar)

You would then use a javascript file like the one here:

https://github.com/statsmodels/statsmodels.github.io/

https://github.com/statsmodels/statsmodels.github.io/blob/master/versions.json

This would then be picked up by all of your document versions, like it is in statsmodels.  https://github.com/statsmodels/statsmodels.github.io/ is a good example of what I am describing.

**Comment by ScriptAutomate** [comment]
Thanks! It was definitely a misunderstanding on my part. I'll close this issue :)
