### ISSUE TITLE
Images not aligned to center when :align: center is specified

### ISSUE THREAD

**Issue by johnthagen** [bashtage/sphinx-material#64]
If I create some RST like:

```
.. image:: ../my_image.png
  :align: center
  :scale: 60%
```

I noticed that unlike vanilla Sphinx the image is not aligned to the center of the page, and is still right justified instead.

- [reference to docs about `.. image::`](https://docutils.sourceforge.io/docs/ref/rst/directives.html#images)

**Comment by johnthagen** [comment]
I played around and confirmed that other `.. image::` directives, like `:scale:` do work. Only one that I can find that doesn't work is `:align:`.

**Comment by johnthagen** [comment]
@bashtage I'd like to try to help out with this issue. Could you point me in the direction where this would be added/fixed?

**Comment by johnthagen** [comment]
I was able to reproduce this on the demo site but updating `docs/index.rst` to:

```rst
===================
Material for Sphinx
===================

.. image:: images/screenshot.png
    :alt: Material for Sphinx Screenshots
    :scale: 20%
    :align: center

...
```

Note that image is not aligned to center. Also `right` does not align it to the right.

<img width="916" alt="material-bug" src="https://user-images.githubusercontent.com/10340167/92414686-52970600-f123-11ea-83c7-fd67bcc5a97d.png">

**Comment by johnthagen** [comment]
When I inspect the element, I see that the `align-center`  class is being applied, so perhaps just some CSS is missing?

<img width="737" alt="inspect-material" src="https://user-images.githubusercontent.com/10340167/92414852-13b58000-f124-11ea-96e8-076e1076698d.png">

**Comment by johnthagen** [comment]
Built example in case someone wants to manually inspect the output:

- [sphinx-material-image-not-aligned-html.zip](https://github.com/bashtage/sphinx-material/files/5184849/sphinx-material-image-not-aligned-html.zip)

**Comment by bashtage** [comment]
I assume that there is no css for img.align-center or img.align-right.

**Comment by johnthagen** [comment]
Thanks, where would the best place to add this be?

**Comment by johnthagen** [comment]
Confirmed that the CSS was missing. I was able to temporarily work around this issue by including the following custom CSS in my Sphinx project:

```py
# conf.py
def setup(app) -> None:
    app.add_css_file('css/custom.css')
```

```css
/* custom.css */
.align-center {
  display: block;
  margin-left: auto;
  margin-right: auto;
}
```

**Comment by johnthagen** [comment]
It appears that `.. list-table::` are not also aligned when `sphinx-material` is applied.

```rst
.. list-table:: Table
   :header-rows: 1
   :align: center

   ...
```
