### ISSUE TITLE
Side bar links always shown as blue instead of white/black

### ISSUE THREAD

**Issue by johnthagen** [bashtage/sphinx-material#65]
On the example page:

https://bashtage.github.io/sphinx-material/index.html#

<img width="1266" alt="sphinx-material" src="https://user-images.githubusercontent.com/10340167/91849505-30385080-ec2a-11ea-8c59-670e82e986de.png">

The title bar text links are white and the side bar links are black and turn to blue when selected.

But when I try a simple configuration:

```py
html_sidebars = {
    "**": ["logo-text.html", "globaltoc.html", "localtoc.html", "searchbox.html"]
}

html_theme = 'sphinx_material'

html_theme_options = {
    'nav_title': 'Test',
}
```

All of my links are blue even before or after clicking. I've tried changing `color_*` and `theme_color` but haven't been able to emulate what the demonstration site is doing.

<img width="213" alt="Screen Shot 2020-09-01 at 8 08 41 AM" src="https://user-images.githubusercontent.com/10340167/91849665-607fef00-ec2a-11ea-9c2a-6017da8ec860.png">

**Comment by johnthagen** [comment]
Also, it seems to always append "documentation" after whatever I set as my `project` in my `conf.py`. Is there a way to disable it auto-appending "documentation" to that name?

**Comment by bashtage** [comment]
> Also, it seems to always append "documentation" after whatever I set as my `project` in my `conf.py`. Is there a way to disable it auto-appending "documentation" to that name?

You need to override the name of your site in your conf.py.  See the demo site's conf. You can verify that the demo site is simply called Material for Sphinx.

**Comment by bashtage** [comment]
You need to set these two keys to your preferred (and supported) color.

```
   # Set the color and the accent color
    'color_primary': 'blue',
    'color_accent': 'light-blue',
```

**Comment by johnthagen** [comment]
> You need to override the name of your site in your conf.py.

Thanks this led me to find the `html_title` attribute, which is what needed to be set. The string was also in `project`, so I didn't find it immediately.

https://github.com/bashtage/sphinx-material/blob/fadb297f10f345ecb8b8fc1ae8964962a24bb81c/docs/conf.py#L28

**Comment by johnthagen** [comment]
Even after setting the `color_` fields, unselected links still appear blue instead of black (like the demo site). Hover and selected links show the `color_` fields properly.

```py
html_title = 'Test'

html_sidebars = {
    "**": ["logo-text.html", "globaltoc.html", "localtoc.html", "searchbox.html"]
}

html_theme = 'sphinx_material'

html_theme_options = {
    'nav_title': 'Test',
    'color_primary': 'green',
    'color_accent': 'red',
}
```

<img width="219" alt="Screen Shot 2020-09-01 at 11 13 15 AM" src="https://user-images.githubusercontent.com/10340167/91869679-291e3c00-ec44-11ea-99df-7569c73f2aa0.png">

Versus (demo site):

<img width="228" alt="Screen Shot 2020-09-01 at 11 13 47 AM" src="https://user-images.githubusercontent.com/10340167/91869758-3f2bfc80-ec44-11ea-969e-e8474afac960.png">

**Comment by bashtage** [comment]
What happens when you make the changes to the docs site?  Does it appear
wrong?

**Comment by johnthagen** [comment]
@bashtage Many apologies, I was working with an existing Sphinx/RTD project and just remembered we added a bit of custom CSS. When I removed it everything looked correct and matched the demo site.

Thank you for this really nice project!

**Comment by johnthagen** [comment]
For anyone else who might find this thread, if you want to remove the secondary top level link on the page:

```py
html_theme_options = {
    ...
    'master_doc': False,
}
```

As documented here: https://bashtage.github.io/sphinx-material/customization.html#configuration-options
