### ISSUE TITLE
Hex colors not supported for color_primary and color_accent

### ISSUE THREAD

**Issue by johnthagen** [bashtage/sphinx-material#66]
When setting `'color_primary': '#FFFF00',` (yellow), the top bar ends up being colored purple (regardless of the hex code input). Is this a bug?

<img width="353" alt="Screen Shot 2020-09-01 at 8 20 57 AM" src="https://user-images.githubusercontent.com/10340167/91850768-16980880-ec2c-11ea-90cb-87b8267e1d63.png">

**Comment by bashtage** [comment]
You can only use the list of colors specified in the configuration file.  These are many precomputed css values that depend on one of the colors being specified.

**Comment by johnthagen** [comment]
Thanks for the information. Sorry for the basic question, but where would one find the configuration file to reference the possible options?

**Comment by bashtage** [comment]
You get it when you create a sphinx site.  If you clone this repo, you will see it in the docs folder.  If you build the docs folder, you will have a perfect replica of the documentation site. Editing these files is a simple way to get started.

**Comment by johnthagen** [comment]
In case someone else finds this issue, the available options are documented here: https://bashtage.github.io/sphinx-material/customization.html#configuration-options

color_primary
- Primary colo. Options are red, pink, purple, deep-purple, indigo, blue, light-blue, cyan, teal, green, light-green, lime, yellow, amber, orange, deep-orange, brown, grey, blue-grey, and white.

color_accent
- Accent color. Options are red, pink, purple, deep-purple, indigo, blue, light-blue, cyan, teal, green, light-green, lime, yellow, amber, orange, and deep-orange.

**Comment by ri0t** [comment]
How much work would it take to convert the css to dynamic coloring? I totally like the whole setup - except the limited color options :-)

**Comment by bashtage** [comment]
@ri0t  Supporting arbitrary colors would be a near-complete rewrite of the CSS.  The CSS relies heavily on the named and precomputed colors.
