### ISSUE TITLE
Copy button for snippets

### ISSUE THREAD

**Issue by MaxHalford** [bashtage/sphinx-material#7]
Hey. Not sure this is in scope or not. Maybe it would be nice to add a copy button to each snippet, like what is done [here](https://www.tensorflow.org/api_docs/python/tf/data/Dataset#shuffle). Maybe be using [clipboard.js](https://clipboardjs.com/)?

**Comment by bashtage** [comment]
I'm not sure this is simple since it isn't easy to ensure that an appropriate class is added to snippets. 

I think something would need to be added to code-block,

https://www.sphinx-doc.org/es/master/usage/restructuredtext/directives.html#directive-code-block

like the option to add a user class.

Perhaps rst-class would be enough? Although this would require changing code and couldn't just be added using a conf option.

**Comment by mgeier** [comment]
FYI: there is https://github.com/choldgraf/sphinx-copybutton

I don't know if it works with this theme, though.

**Comment by bashtage** [comment]
Would be good to add it.  I was thinking it would be configurable.  If sphinx-copybutton works, then I suppose could just suggest that rather than rolling a hone-grown solution.

**Comment by carrascomj** [comment]
It [works](https://dynamic-fba.readthedocs.io/en/latest/installation.html), although it has got a slight glitch with the jupyter notebook's codeblocks (you can see that it has one extra button on the left of every codeblock [here](https://dynamic-fba.readthedocs.io/en/latest/installation.html)).

**Comment by mgeier** [comment]
This is actively being worked on in https://github.com/spatialaudio/nbsphinx/pull/349

Please leave your feedback there!

**Comment by mgeier** [comment]
I've just released `nbsphinx` version 0.5.1 which should fix the glitches with sphinx-copybutton.

Here's how Jupyter notebooks look with the sphinx-material theme and with sphinx-copybutton enabled: https://nbsphinx.readthedocs.io/en/material-theme/code-cells.html.

**Comment by carrascomj** [comment]
Thanks! I confirm It woks like a charm: https://dynamic-fba.readthedocs.io/en/latest/example1.html

**Comment by bashtage** [comment]
Looks great!

**Comment by MaxHalford** [comment]
Just set it up, looks really nice!
