### ISSUE TITLE
Missing global TOC

### ISSUE THREAD

**Issue by StefanUlbrich** [bashtage/sphinx-material#73]
Hi, thanks for this amazing theme!

However, for me the global TOC does not appear on the left. I use sphinx version 3.2.1. . I copied the default html_theme_options (on the readme) and added `"version_dropdown": False`. The console shows a single error:

```
application.js:244 Uncaught TypeError: Cannot read property 'style' of undefined
    at e.t.reset (application.js:244)
    at e.t.unlisten (application.js:74)
    at MediaQueryList.MatchMedia.handler_ (application.js:79)
t.reset @ application.js:244
t.unlisten @ application.js:74
MatchMedia.handler_ @ application.js:79
```

**Comment by bashtage** [comment]
You also need this in conf.py

https://github.com/bashtage/sphinx-material/blob/0b27752e833cf3f77c1d7fcb1194e7c005c8870d/docs/conf.py#L81

**Comment by StefanUlbrich** [comment]
Thanks for very quick answer. With `html_sidebars` set, the global TOC shows up.

**Comment by 2bndy5** [comment]
I ran across this problem as well. Reading this thread fixed it, but shouldn't this info be in the readme?

BTW, I'm loving the work here!
