### ISSUE TITLE
Show icons for external links

### ISSUE THREAD

**Issue by yikeke** [bashtage/sphinx-material#77]
Hi,
First, lots of thanks for providing this pretty theme.

My question is: does this theme provide a way to show an icon after each external link?

Example:
![image](https://user-images.githubusercontent.com/61895496/94711018-25342580-037a-11eb-9c06-1eb7f3e0a9a5.png)

Thanks,
Coco

**Comment by bashtage** [comment]
I think you can do this using your site's custom CSS file.

https://krasimirtsonev.com/blog/article/CSS-before-and-after-pseudo-elements-in-practice

**Comment by yikeke** [comment]
👍 Thanks for the information. I'll try it.

**Comment by bashtage** [comment]
Thanks. Closing since no changes needed.
