### ISSUE TITLE
How to fix GET time out?

### ISSUE THREAD

**Issue by luhuadong** [bashtage/sphinx-material#83]
Hi, I am using this theme for my docs, and I access the web pages via broswer from China. Always get an error, like this:

```
GET https://fonts.googleapis.com/css?family=Roboto+Mono:400,500,700|Roboto:300,400,400i,700&display=fallback net::ERR_TIMED_OUT
```

So, everytime I have to wait a few seconds until time out. Is it necessary add this link in layout.html? And how can I (and so many Chinese) aviod this error?

Thanks! :heart:

**Comment by bashtage** [comment]
I think googleapis is probably blocked in your location.  You can replace this block by overriding here:

https://github.com/bashtage/sphinx-material/blob/ec5690054e10fd6deb91f67fbb6074a738da6681/sphinx_material/sphinx_material/layout.html#L24
