### ISSUE TITLE
Background color of code block

### ISSUE THREAD

**Issue by haizaar** [bashtage/sphinx-material#9]
Good day. First of all - awesome project!

For some reason all code block backgrounds are yellow: 
![image](https://user-images.githubusercontent.com/58201/68824610-895ee400-06eb-11ea-8e0f-74447faa929b.png)

While in your examples they are gray. Do you have an idea why and how do I control it? I tried comparing my config with yours in this repo and didn't find any relevant knobs.

Thank you!

**Comment by haizaar** [comment]
Never mind - I had a `pygments_style = "sphinx"` in my `conf.py`

**Comment by bashtage** [comment]
You need to set pygments_style.

**Comment by bashtage** [comment]
Thanks for the compliments.
