### ISSUE TITLE
Font size of admonitions larger than regular text

### ISSUE THREAD

**Issue by rgommers** [bashtage/sphinx-material#91]
Examples from https://bashtage.github.io/sphinx-material/additional_samples.html#admonitions:

<img width="365" alt="image" src="https://user-images.githubusercontent.com/98330/103369825-6b109f00-4acb-11eb-9131-3c3e0d80ca4f.png">

Regular text is `0.8rem` while the text in admonitions is `0.85rem`. The visual difference is quite large, and imho doesn't look good. I don't think this difference was done on purpose?

**Comment by bashtage** [comment]
This was fixed a long time ago but I failed to release.  Thanks for the reminder.
