### ISSUE TITLE
Question: Can you adjust the width of the body of a page?

### ISSUE THREAD

**Issue by jamesETsmith** [bashtage/sphinx-material#97]
Thanks for making this package, it was really easy to use for a website I'm helping set up!

Is there any way to adjust the width of the body of the page? Should I use the `_templates/layout.html` you mention in the `README.md` or is there some simpler way?

Thanks!

**Comment by bashtage** [comment]
This should only require using your own CSS file to override the defaults.  Because there are a lot of @media selects, it might take quite a bit of work.
