### ISSUE TITLE
Build Your Docs?

### ISSUE THREAD

**Issue by eightbit** [bashtage/sphinx-material#98]
Thanks for creating this cool theme!

I'm trying to build your docs to get a better look at how it works. I've downloaded the docs folder, run requirements.txt and build using:
`sphinx-build -b html . _build`
I get a series of errors like
```
c:\programdata\anaconda3\envs\sphinx\lib\site-packages\recommonmark\parser.py:75: UserWarning: Container node skipped: type=document
  warn("Container node skipped: type={0}".format(mdnode.t))
c:\programdata\anaconda3\envs\sphinx\lib\site-packages\numpy\polynomial\polynomial.py:docstring of numpy.polynomial.polynomial.Polynomial.rst:42: WARNING: autosummary: stub file not found 'numpy.polynomial.Polynomial.__call__'. Check your autosummary_generate setting.
...
Notebook error:
ImportError in notebook.ipynb:
DLL load failed while importing win32api: The specified module could not be found.
```
Note that I'm able to build a different set of docs with Material.
Is there a simple fix for this?
Thanks.

**Comment by bashtage** [comment]
Do you have all of the requirements in your vitual env?  The requirements file is in the docs folder.

**Comment by bashtage** [comment]
```
DLL load failed while importing win32api: The specified module could not be found.
```

indicates something isn't right with your environment.

**Comment by bashtage** [comment]
This fix is a bit of a pain:

https://stackoverflow.com/questions/58612306/how-to-fix-importerror-dll-load-failed-while-importing-win32api

I've hit this myself.

**Comment by eightbit** [comment]
Thanks for the quick reply!
I've run into issues like this in the past - very frustrating.
In this case you pointed me straight to the answer, which in my case it:
`conda install pywin32`

The docs now compile, including with autobuild:

`sphinx-autobuild . --port 8020 _build/html`
But I still get a series of non-fatal errors related to numpy
```
c:\programdata\anaconda3\envs\sphinx\lib\site-packages\recommonmark\parser.py:75: UserWarning: Container node skipped: type=document
  warn("Container node skipped: type={0}".format(mdnode.t))
reading sources... [100%] subpage/subsubpage
c:\programdata\anaconda3\envs\sphinx\lib\site-packages\numpy\polynomial\polynomial.py:docstring of numpy.polynomial.polynomial.Polynomial.rst:42: WARNING: autosummary: stub file not found 'numpy.polynomial.Polynomial.__call__'. Check your autosummary_generate setting.
...
```
and these 3:
```
D:\Projects\IABLE\Documentation\sphinx-material-master\docs\markdown.md:18: WARNING: None:any reference target not found: #
D:\Projects\IABLE\Documentation\sphinx-material-master\docs\markdown.md:54: WARNING: None:any reference target not found: #
D:\Projects\IABLE\Documentation\sphinx-material-master\docs\markdown.md:172: WARNING: None:any reference target not found: #
```

**Comment by bashtage** [comment]
The final 3 are expected.  The first is probably something to do with autodoc or numpydoc which is creating the bad link.
