### ISSUE TITLE
TOC Not Showing in Left Sidebar

### ISSUE THREAD

**Issue by eightbit** [bashtage/sphinx-material#99]
When I build my docs site, the left sidebar is empty. There are no build errors and the site seems to be working otherwise.
In **index.rst** I have:
```
.. toctree::
    :caption: Basic Use
    :maxdepth: 1

    docs/testMe01.md
    docs/numpydoc.rst
```
My files structure:
```
Root
--Source
--Docs
--index.rst
--conf.py
```
From Root I'm running
`sphinx-autobuild source build/html`

Do I need to have a specific arrangement of the dirs/files?
Obvious fix?
Thanks.

**Comment by JeremiAnastaziak** [comment]
https://github.com/bashtage/sphinx-material/issues/73

**Comment by bashtage** [comment]
Does 73 fix your problem.

**Comment by bashtage** [comment]
I am guess it does.
